spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mshop
    username: root
    password: obviouslynotall8390038
  main:
    allow-circular-references: true
  mail:
    host: smtp.yandex.ru
    username: pic.shop@yandex.ru
    password: "zagbvqambosttddz"
    port: 465
    protocol: smtps